Repository steelesh/UCollab, pull requests merged in 2024-12, with the labels that each got.

#86 create page & explore page with API endpoints
  package-lock.json
  package.json
  prisma/schema.prisma
  prisma/seed.ts
  public/project.svg
  src/pages/[username].tsx
  src/pages/api/users/from-id/[id].ts
  src/pages/create.tsx
  src/pages/explore.tsx
  src/schemas/post.schema.ts
  src/types/post.types.ts
Labels: fullstack

#91 remove unused db models and usages
  prisma/schema.prisma
Labels: database

#92 implement digitalocean blob storage
  next.config.js
  package-lock.json
  package.json
  src/env.js
  src/lib/utils/user-photo.ts
Labels: backend, database

#94 fix username page slug
  src/pages/community.tsx
  src/pages/users/[username].tsx
Labels: frontend
